Kickoff
wolox-training/mt-netcore pull request #1
Opened 2017-08-10 22:23 UTC by truccomarcos

# Summary
- Kickoff
- Controllers
- Views
- Model
- MIgrations

# Trello Cards
- https://trello.com/c/aRAtMKsn/1-kick-off
- https://trello.com/c/Eyg5zCMv/3-mvc-controllers
- https://trello.com/c/g6yqSga6/4-mvc-views
- https://trello.com/c/DWUmdK9n/5-mvc-models
- https://trello.com/c/mcVxer9f/6-migrations

2017-08-11 19:41 UTC, gussiciliano requested changes

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/.vscode/launch.json
> +{
ignore all .vscode/ files

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +}
add empty line

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +        //
delete empty comment

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +        //
delete empty comment

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HelloWorldController.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HomeController.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Controllers/HomeController.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Models/Movie.cs
> +}
add final line

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/MvcMovie.csproj
> +    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
merge ItemGoup tags

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Program.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Program.cs
> +
delete empty space

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Views/HelloWorld/Index.cshtml
> +<p>Hello from our View Template!</p>
add final line

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/Views/HelloWorld/Welcome.cshtml
> +    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
why do you do this?
i don't remember the card jeje

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/appsettings.json
> +  }
add final line

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/bin/Debug/netcoreapp1.1/MvcMovie.runtimeconfig.dev.json
> +{
ignore all bin files

2017-08-11 19:41 UTC, gussiciliano commented on MvcMovie/obj/Debug/netcoreapp1.1/CoreCompileInputs.cache
> +d7671eeb299a1b0216fa93fc9f90c61a58492715
ignore all obj files

2017-08-11 21:16 UTC, truccomarcos commented on MvcMovie/Views/HelloWorld/Welcome.cshtml
> +    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
I think it came from one of the tutorials

2017-08-14 15:08 UTC, gussiciliano approved these changes
just little comment :P

2017-08-14 15:08 UTC, gussiciliano commented on MvcMovie/.gitignore
> +.vscode/
add final line

2017-08-14 15:08 UTC, gussiciliano commented on MvcMovie/Views/HelloWorld/Welcome.cshtml
> +    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
oks :P

2017-08-14 21:44 UTC, merged